name: Trigger Another Repository Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-other-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        uses: actions/github-script@v3
        with:
          script: |
            const octokit = require("@octokit/rest")();
            octokit.authenticate({
              type: "token",
              token: "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"
            });
            octokit.repos.createDispatchEvent({
              owner: "Nandani568",
              repo: "test_workflow",
              event_type: "run-workflow",
              client_payload: {
                workflow_id: 4352206 # Replace this with the ID of the workflow you want to trigger
              }
            });
